version: '3.8'

services:
  code-server:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../workspace:/home/vscode/workspace
      - ./config:/home/vscode/.config
    restart: unless-stopped
